// data.js 文件内容
const PRODUCTS = [
  {
        id: 1,
        name: "プレミアム ケーブルニット ペットウェア",
        category: "ペット用品",
        price: 8900,
        stock: 15,
        badge: "new",
        image: "images/IMG_5169.jpg",
        image2: "images/IMG_5274.JPG",
        images: [
          "images/IMG_5275.JPG",
          "images/IMG_5276.JPG"
        ],
        colors: [
          { name: "Off White", priceModifier: 0 },
          { name: "Camel", priceModifier: 500 }
        ],
        sizes: [
          { name: "S", priceModifier: 0 },
          { name: "M", priceModifier: 0 },
          { name: "L", priceModifier: 300 }
        ],
        desc: "上質なハイゲージニットを使用した、ラグジュアリーなペットウェア。洗練されたぬくもりを大切な家族に。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "高級ウール 80%、カシミヤ 20%",
        notice: "※本製品はデリケートなウール素材を使用しているため、手洗いまたはネットに入れてのドライコースを推奨いたします。タンブラー乾燥はお避けください。"
      },
      {
        id: 2,
        name: "オーガニックコットン プレイスマット",
        category: "ペット用品",
        price: 3400,
        stock: 20,
        badge: "",
        image: "images/products/pet-02-front.jpg",
        images: ["images/products/pet-02-front.jpg"],
        colors: [{ name: "Natural", priceModifier: 0 }, { name: "Sage", priceModifier: 0 }],
        sizes: [{ name: "Free", priceModifier: 0 }],
        desc: "お食事の時間をエレガントに演出する、撥水加工を施したオーガニックコットンのマットです。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "オーガニックコットン 100%（表面耐水パラフィン加工）",
        notice: "※汚れた場合は固く絞った布で拭き取ってください。洗濯機で何度も洗うと撥水効果が徐々に薄れる場合がございます。"
      },
      {
        id: 3,
        name: "スタイリッシュ フードボウル (セラミック)",
        category: "ペット用品",
        price: 4800,
        stock: 8,
        badge: "hot",
        image: "images/products/pet-03-front.jpg",
        images: ["images/products/pet-03-front.jpg"],
        colors: [{ name: "Black", priceModifier: 0 }, { name: "White", priceModifier: 0 }],
        sizes: [{ name: "Regular", priceModifier: 0 }],
        desc: "美濃焼の職人が一つ一つ丁寧に仕上げた、インテリアに溶け込むモダンなフードボウル。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "磁器（美濃焼）",
        notice: "※電子レンジ・食洗機対応。職人による手作りのため、釉薬のムラやわずかな気泡が見られる場合がありますが、風合いとしてお楽しみください。"
      },
      {
        id: 4,
        name: "クラシック リネンリード",
        category: "ペット用品",
        price: 5200,
        stock: 12,
        badge: "",
        image: "images/products/pet-04-front.jpg",
        images: ["images/products/pet-04-front.jpg"],
        colors: [{ name: "Taupe", priceModifier: 0 }, { name: "Navy", priceModifier: 0 }],
        sizes: [{ name: "1.2m", priceModifier: 0 }],
        desc: "使うほどに手に馴染む上質なリネンと、真鍮製パーツを組み合わせた高級感のあるリードです。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "アイリッシュリネン 100%、高級真鍮金具",
        notice: "※安全のため、ご使用前に傷や擦れがないか必ず点検してください。水濡れした場合は陰干しで完全に乾かしてください。"
      },
      {
        id: 5,
        name: "コンフォート リネンカラー (首輪)",
        category: "ペット用品",
        price: 3800,
        stock: 0,
        badge: "",
        image: "images/products/pet-05-front.jpg",
        images: ["images/products/pet-05-front.jpg"],
        colors: [{ name: "Taupe", priceModifier: 0 }, { name: "Navy", priceModifier: 0 }],
        sizes: [{ name: "S", priceModifier: 0 }, { name: "M", priceModifier: 200 }],
        desc: "肌当たりの優しいリネン素材。ワンポイントの真鍮金具がシックな印象を与えます。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "アイリッシュリネン 100%、真鍮",
        notice: "※サイズはお出かけ前に指が1〜2本入る程度の隙間があるかご確認ください。強い引っ張り癖のあるペットへのご使用はご注意ください。"
      },
      {
        id: 6,
        name: "トラベル ペットキャリーバッグ",
        category: "ペット用品",
        price: 18900,
        stock: 5,
        badge: "new",
        image: "images/products/pet-06-front.jpg",
        images: ["images/products/pet-06-front.jpg"],
        colors: [{ name: "Charcoal", priceModifier: 0 }],
        sizes: [{ name: "Standard", priceModifier: 0 }],
        desc: "耐久性と通気性に優れた、高機能でおしゃれな移動用キャリーバッグ。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "高密度バリスティックナイロン、ヴィーガンレザー、アルミフレーム",
        notice: "※耐荷重は8kgまでとなります。公共交通機関でご使用の際は、各運行会社の規定をあらかじめご確認ください。"
      },
      {
        id: 7,
        name: "リラクシング キャットベッド",
        category: "ペット用品",
        price: 12000,
        stock: 7,
        badge: "",
        image: "images/products/pet-07-front.jpg",
        images: ["images/products/pet-07-front.jpg"],
        colors: [{ name: "Beige", priceModifier: 0 }, { name: "Gray", priceModifier: 0 }],
        sizes: [{ name: "Free", priceModifier: 0 }],
        desc: "包み込まれるような安心感を与えるフォルム。インテリアの邪魔をしないニュアンスカラー。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "リネンウール混紡（本体外側）、低反発ウレタンフォーム（クッション内部）",
        notice: "※内側のクッションカバーは取り外して洗濯機で洗えます。ウレタン本体は洗濯できませんので、日陰干ししてください。"
      },
      {
        id: 8,
        name: "天然木 キャットタワー ミニ",
        category: "ペット用品",
        price: 24500,
        stock: 3,
        badge: "",
        image: "images/products/pet-08-front.jpg",
        images: ["images/products/pet-08-front.jpg"],
        colors: [{ name: "Oak", priceModifier: 0 }],
        sizes: [{ name: "H110cm", priceModifier: 0 }],
        desc: "天然木を使用し、日本の住空間に合わせてコンパクトに設計された美しいキャットタワー。",
        origin: "大阪府より発送",
        delivery: "ご注文後、2〜4営業日以内に発送",
        material: "天然オーク材（無垢）、最高級麻縄",
        notice: "※こちらは組み立て式の家具となります（工具同梱）。転倒防止のため、必ず水平で頑丈な壁際に設置してください。"
      },
      {
        id: 9,
        name: "プレミアム ケアブラシ",
        category: "ペット用品",
        price: 4200,
        stock: 25,
        badge: "",
        image: "images/products/pet-09-front.jpg",
        images: ["images/products/pet-09-front.jpg"],
        colors: [{ name: "Walnut", priceModifier: 0 }],
        sizes: [{ name: "One Size", priceModifier: 0 }],
        desc: "ペットの皮膚を傷つけず、無駄毛を優しく取り除く天然木ハンドルの最高級ブラシ。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "天然ウォルナット材、極細ステンレスピン（先端保护ラバー加工）",
        notice: "※皮膚に炎症がある場合や、毛玉がひどい場合は無理に引っ張らず、優しくほぐすようにブラッシングしてください。"
      },
      {
        id: 10,
        name: "ボタニカル ペットシャンプー",
        category: "ペット用品",
        price: 2900,
        stock: 30,
        badge: "",
        image: "images/products/pet-10-front.jpg",
        images: ["images/products/pet-10-front.jpg"],
        colors: [{ name: "Lavender & Chamomile", priceModifier: 0 }],
        sizes: [{ name: "300ml", priceModifier: 0 }],
        desc: "天然由来成分100%。デリケートな肌をやさしく洗い上げ、ほのかに香るボタニカルシャンプー。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "有機カモミールエキス、ラベンダー精油、植物由来洗浄成分",
        notice: "※目や耳に入らないようにご注意ください。万が一、使用中または使用後に皮膚の異常が現れた場合は直ちに使用を中止し、獣医師にご相談ください。"
      },

      // ==========================================
      // SECTION 2: ファッション・アクセサリー / FASHION (ID: 11 ~ 20)
      // ==========================================
      {
        id: 11,
        name: "シルクリネン ライトストール",
        category: "ファッション・アクセサリー",
        price: 12000,
        stock: 14,
        badge: "new",
        image: "images/products/fsh-01-front.jpg",
        images: ["images/products/fsh-01-front.jpg"],
        colors: [{ name: "Pale Pink", priceModifier: 0 }, { name: "Sky Blue", priceModifier: 0 }, { name: "Linen", priceModifier: 0 }],
        sizes: [{ name: "Free", priceModifier: 0 }],
        desc: "極上のシルクとリネンを織り交ぜた、空気のように軽い大判ストール。春夏の紫外線・冷房対策に。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "シルク 55%、リネン 45%",
        notice: "※非常に繊浅な織物ですので、引っかかりにご注意ください。お洗濯は信頼のおけるクリーニング店へご相談いただくか、優しく手洗いしてください。"
      },
      {
        id: 12,
        name: "ミニマル レザーカードケース",
        category: "ファッション・アクセサリー",
        price: 7800,
        stock: 18,
        badge: "",
        image: "images/products/fsh-02-front.jpg",
        images: ["images/products/fsh-02-front.jpg"],
        colors: [{ name: "Black", priceModifier: 0 }, { name: "Etain", priceModifier: 0 }, { name: "Gold", priceModifier: 0 }],
        sizes: [{ name: "Free", priceModifier: 0 }],
        desc: "厳選されたイタリアンレザーを使用。無駄を削ぎ落としたミニマルな美しいデザイン。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "牛革（イタリア製トゴレザー）",
        notice: "※天然皮革を使用しているため、自然なシワやシボの個体差があります。水濡れはシミの原因となりますので、濡れた場合はすぐに乾いた柔らかい布で拭き取ってください。"
      },
      {
        id: 13,
        name: "クラシック パナマハット",
        category: "ファッション・アクセサリー",
        price: 16500,
        stock: 6,
        badge: "",
        image: "images/products/fsh-03-front.jpg",
        images: ["images/products/fsh-03-front.jpg"],
        colors: [{ name: "Natural", priceModifier: 0 }],
        sizes: [{ name: "M (57cm)", priceModifier: 0 }, { name: "L (59cm)", priceModifier: 0 }],
        desc: "エクアドル産の本格パナマ草を手編みした、コーディネートを格上げするハット。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "天然トキヤ草（パナマ草）100%、レーヨン（リボン部分）",
        notice: "※型崩れを防ぐため、つばの縁を持ってお取り扱いください。水洗いはできません。保管 of 際は乾燥した涼しい場所で箱に入れて保管してください。"
      },
      {
        id: 14,
        name: "シアーソックス (3足セット)",
        category: "ファッション・アクセサリー",
        price: 3900,
        stock: 40,
        badge: "",
        image: "images/products/fsh-04-front.jpg",
        images: ["images/products/fsh-04-front.jpg"],
        colors: [{ name: "Monotone Set", priceModifier: 0 }, { name: "Earth Set", priceModifier: 0 }],
        sizes: [{ name: "23-25cm", priceModifier: 0 }],
        desc: "絶妙な透け感と上品な光沢。パンプスにもサンダルにも合わせやすい上質な一足。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "ナイロン、ポリウレタン、ポリエステル",
        notice: "※大変薄く繊細な生地です。爪や指輪などによる引っかかり、伝線に十分ご注意ください。お洗濯の際は必ず目の細かいネットに入れてください。"
      },
      {
        id: 15,
        name: "ヴィンテージライク 真鍮バングル",
        category: "ファッション・アクセサリー",
        price: 6400,
        stock: 11,
        badge: "hot",
        image: "images/products/fsh-05-front.jpg",
        images: ["images/products/fsh-05-front.jpg"],
        colors: [{ name: "Brass Gold", priceModifier: 0 }],
        sizes: [{ name: "Slim", priceModifier: 0 }, { name: "Wide", priceModifier: 800 }],
        desc: "経年変化を楽しめる真鍮バングル。手元にクラシカルなアクセントを添えます。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "ソリッドブラス（無垢真鍮）",
        notice: "※真鍮の特性上、空気に触れることで徐々にアンティーク調の色味へ変化します。輝きを戻したい場合は、市販の真鍮磨きクロスなどで優しく磨いてください。"
      },
      {
        id: 16,
        name: "アコヤ真珠 ミニマルピアス",
        category: "ファッション・アクセサリー",
        price: 24000,
        stock: 4,
        badge: "new",
        image: "images/products/fsh-06-front.jpg",
        images: ["images/products/fsh-06-front.jpg"],
        colors: [{ name: "K18 Yellow Gold", priceModifier: 0 }],
        sizes: [{ name: "6.0mm", priceModifier: 0 }],
        desc: "伊勢志摩産の上質なアコヤ真珠を使用。普段使いからフォーマルまで気品溢れる仕上がりに。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "伊勢志摩産アコヤ本真珠、K18イエローゴールド（ポスト・キャッチ部）",
        notice: "※真珠は酸や汗に弱い性質があります。ご使用後は、柔らかいクロス等で優しく汗や皮脂を拭き取ってから保管してください。"
      },
      {
        id: 17,
        name: "キャンバス 2WAY トートバッグ",
        category: "ファッション・アクセサリー",
        price: 13500,
        stock: 9,
        badge: "",
        image: "images/products/fsh-07-front.jpg",
        images: ["images/products/fsh-07-front.jpg"],
        colors: [{ name: "Ivory", priceModifier: 0 }, { name: "Olive", priceModifier: 0 }],
        sizes: [{ name: "Free", priceModifier: 0 }],
        desc: "厚手の強靭なキャンバス地と上質なヌメ革を使用。経年変化が楽しみな2WAYバッグ。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "6号倉敷帆布（綿100%）、国産ヌメ革",
        notice: "※キャンバス生地の特性上、水濡れや摩擦により色落ち・衣類への色移りが発生する場合があります。特に雨の日のご使用にはご注意ください。"
      },
      {
        id: 18,
        name: "フレンチリネン エプロンドレス",
        category: "ファッション・アクセサリー",
        price: 9800,
        stock: 15,
        badge: "",
        image: "images/products/fsh-08-front.jpg",
        images: ["images/products/fsh-08-front.jpg"],
        colors: [{ name: "Charcoal", priceModifier: 0 }, { name: "Flax", priceModifier: 0 }],
        sizes: [{ name: "Free", priceModifier: 0 }],
        desc: "美しく身体を包み込むドレスのようなエプロン。家の中での時間をさらに豊かに。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "フランス産リネン 100%",
        notice: "※麻特有のネップ（糸の節）が見られる場合がありますが、天然素材の風合いです。洗濯後はシワを伸ばし、形を整えてから陰干ししてください。"
      },
      {
        id: 19,
        name: "UVカット オーガニックコットン日傘",
        category: "ファッション・アクセサリー",
        price: 14000,
        stock: 0,
        badge: "",
        image: "images/products/fsh-09-front.jpg",
        images: ["images/products/fsh-09-front.jpg"],
        colors: [{ name: "Striped Beige", priceModifier: 0 }],
        sizes: [{ name: "47cm", priceModifier: 0 }],
        desc: "竹製のハンドルと天然素材の生地が涼しげな、完全遮光仕様の高級日傘。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "オーガニックコットン 100%（裏面UVカット遮光コーティング）、天然竹（持ち手）",
        notice: "※本製品は日傘専用です。激しい豪雨の際などは雨水が染み込む恐れがありますので、雨傘としての常用はお避けください。"
      },
      {
        id: 20,
        name: "ウールフェルト ベレー帽",
        category: "ファッション・アクセサリー",
        price: 6800,
        stock: 22,
        badge: "",
        image: "images/products/fsh-10-front.jpg",
        images: ["images/products/fsh-10-front.jpg"],
        colors: [{ name: "Bordeaux", priceModifier: 0 }, { name: "Noir", priceModifier: 0 }],
        sizes: [{ name: "Free", priceModifier: 0 }],
        desc: "なめらかなウールフェルトを贅沢に使用。美しい立体感をキープできる仕立てです。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "ウールフェルト 100%",
        notice: "※水洗いは縮みの原因となりますのでお避けください。汚れた場合は、固く絞った布で叩くように汚れを落とし、陰干ししてください。"
      },

      // ==========================================
      // SECTION 3: 生活雑貨 / LIFESTYLE (ID: 21 ~ 30)
      // ==========================================
      {
        id: 21,
        name: "ボタニカル ソイキャンドル",
        category: "生活雑貨",
        price: 4200,
        stock: 25,
        badge: "new",
        image: "images/products/lfs-01-front.jpg",
        images: ["images/products/lfs-01-front.jpg"],
        colors: [{ name: "Fig & Hinoki", priceModifier: 0 }, { name: "Citrus & Sage", priceModifier: 0 }],
        sizes: [{ name: "200g", priceModifier: 0 }],
        desc: "天然のソイワックスに100%ピュアエッセンシャルオイルをブレンド。木製芯の優しく心地よい音を愉しんで。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "天然大豆ワックス（ソイワックス）100%、天然精油、ウッドウィック（木製芯）",
        notice: "※点火時は芯を5mm程度にカットしてご使用ください。大豆アレルギーをお持ちの方は念のためご使用をお控えいただくか、医師にご相談ください。"
      },
      {
        id: 22,
        name: "リネン ワッフルフェイスタオル",
        category: "生活雑貨",
        price: 2800,
        stock: 35,
        badge: "",
        image: "images/products/lfs-02-front.jpg",
        images: ["images/products/lfs-02-front.jpg"],
        colors: [{ name: "White", priceModifier: 0 }, { name: "Oatmeal", priceModifier: 0 }],
        sizes: [{ name: "Standard", priceModifier: 0 }],
        desc: "吸水性と速乾性に優れたリネン100%のワッフルタオル。使うほどに柔らかく育ちます。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "高品質リネン 100%",
        notice: "※使い始めは特有の繊維くずが出ることがありますので、単独での洗濯をお勧めします。柔軟剤のご使用は吸水性を損なうため、極力お控えください。"
      },
      {
        id: 23,
        name: "ハンドメイド ルームスリッパ",
        category: "生活雑貨",
        price: 5800,
        stock: 12,
        badge: "",
        image: "images/products/lfs-03-front.jpg",
        images: ["images/products/lfs-03-front.jpg"],
        colors: [{ name: "Brown Leather", priceModifier: 0 }, { name: "Suede Gray", priceModifier: 0 }],
        sizes: [{ name: "M (24cm)", priceModifier: 0 }, { name: "L (26cm)", priceModifier: 200 }],
        desc: "職人が一足ずつ手縫いで仕上げた、素足で履きたくなる極上のラム革スリッパ。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "羊革（本体）、スエードレザー（底面・静音加工）",
        notice: "※本製品は室内専用です。本革仕様のため水洗いはできません。革用クリーナーまたは固く絞った布でメンテナンスしてください。"
      },
      {
        id: 24,
        name: "和硝子 手吹きグラス",
        category: "生活雑貨",
        price: 3600,
        stock: 16,
        badge: "hot",
        image: "images/products/lfs-04-front.jpg",
        images: ["images/products/lfs-04-front.jpg"],
        colors: [{ name: "Clear", priceModifier: 0 }, { name: "Amber", priceModifier: 0 }],
        sizes: [{ name: "250ml", priceModifier: 0 }],
        desc: "気泡の入り方や揺らぎが美しい、手吹きならではの温かみを感じるモダンなグラス。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "ソーダガラス（手吹き製法）",
        notice: "※耐熱ガラスではありません。急激な温度変化（熱湯の注ぎ入れや、冷えた状態での電子レンジ使用など）は破損の原因となりますのでお避けください。"
      },
      {
        id: 25,
        name: "ウォルナット ツールスタンド",
        category: "生活雑貨",
        price: 7200,
        stock: 8,
        badge: "",
        image: "images/products/lfs-05-front.jpg",
        images: ["images/products/lfs-05-front.jpg"],
        colors: [{ name: "Natural Walnut", priceModifier: 0 }],
        sizes: [{ name: "High", priceModifier: 0 }],
        desc: "キッチンツールや文房具を美しく収納する、重厚感のある天然木スタンド。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "北米産ブラックウォルナット材（天然木・オイルフィニッシュ）",
        notice: "※水気の多い場所に長時間放置するとカビや反りの原因になります。定期的に植物性オイルを薄く塗ることで、深い色艶を長く保てます。"
      },
      {
        id: 26,
        name: "真鍮製 ミニマリスト一輪挿し",
        category: "生活雑貨",
        price: 4900,
        stock: 20,
        badge: "",
        image: "images/products/lfs-06-front.jpg",
        images: ["images/products/lfs-06-front.jpg"],
        colors: [{ name: "Solid Brass", priceModifier: 0 }],
        sizes: [{ name: "H15cm", priceModifier: 0 }],
        desc: "一輪の花を際立たせる、洗練された真鍮製のフラワーベース。静かな存在感を放ちます。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "真鍮（内側：ガラス試験管同梱）",
        notice: "※水を入れる際は、付属のガラス管をご使用ください。真鍮本体に直接水が長時間触れると、強い緑青（サビ）の原因となります。"
      },
      {
        id: 27,
        name: "手織りオーガニック ルームマット",
        category: "生活雑貨",
        price: 14500,
        stock: 4,
        badge: "",
        image: "images/products/lfs-07-front.jpg",
        images: ["images/products/lfs-07-front.jpg"],
        colors: [{ name: "Ivory & Charcoal", priceModifier: 0 }],
        sizes: [{ name: "50x80cm", priceModifier: 0 }],
        desc: "インドの伝統的な手法で丁寧に手織りされた、インテリアの主役になるラグマット。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "オーガニックコットン 70%、天然ジュート（麻） 30%",
        notice: "※手織りのため、サイズに数センチの個体差がある場合があります。最初のうちは独特の素材臭がすることがあります。気になる場合は陰干ししてください。"
      },
      {
        id: 28,
        name: "ボタニカル ルームミスト",
        category: "生活雑貨",
        price: 3200,
        stock: 30,
        badge: "",
        image: "images/products/lfs-08-front.jpg",
        images: ["images/products/lfs-08-front.jpg"],
        colors: [{ name: "Deep Forest", priceModifier: 0 }, { name: "Morning Sun", priceModifier: 0 }],
        sizes: [{ name: "150ml", priceModifier: 0 }],
        desc: "空間を瞬時にリフレッシュする天然エッセンシャルオイル配合の贅沢なミスト。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "天然植物精油（ヒノキ・シダーウッド等）、植物性エタノール、精製水",
        notice: "※シルクや革製品、白い壁紙などに直接スプレーするとシミになる恐れがあります。対象物から30cm以上離して空間にスプレーしてください。"
      },
      {
        id: 29,
        name: "美濃焼 マット釉 プレート",
        category: "生活雑貨",
        price: 3800,
        stock: 18,
        badge: "new",
        image: "images/products/lfs-09-front.jpg",
        images: ["images/products/lfs-09-front.jpg"],
        colors: [{ name: "Matt Gray", priceModifier: 0 }, { name: "Matt Beige", priceModifier: 0 }],
        sizes: [{ name: "21cm", priceModifier: 0 }],
        desc: "現代の食卓に寄り添う、マットな質感がシックな美濃焼の万能ミディアムプレート。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "陶磁器（美濃焼・マット釉仕上）",
        notice: "※電子レンジ・食洗機対応。オーブンや直火でのご使用はできません。メタルマーク（金属製ナイフ等との摩擦による黒い線）がつきやすいためご注意ください。"
      },
      {
        id: 30,
        name: "オーガニック ハーブティーボックス",
        category: "生活雑貨",
        price: 2600,
        stock: 0,
        badge: "",
        image: "images/products/lfs-10-front.jpg",
        images: ["images/products/lfs-10-front.jpg"],
        colors: [{ name: "Relax Blend", priceModifier: 0 }],
        sizes: [{ name: "20 Bags", priceModifier: 0 }],
        desc: "厳選されたオーガニックハーブのみを使用。1日の終わりに心身を解きほぐすブレンド。",
        origin: "大阪府より発送",
        delivery: "ご注文後、1〜3営業日以内に発送",
        material: "有機カモミール、有機ペパーミント、有機レモングラス（生分解性ティーバッグ使用）",
        notice: "※直射日光・高温多湿を避けて冷暗所に保存してください。開封後は賞味期限に関わらずお早めにお召し上がりください。"
      }
    ];
